spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: password

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  sql:
    init:
      platform: h2

  mail:
    host: localhost
    port: 1025
    username: mail1@tmp.com
    password: 1234 5678 9012 3456
