repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: lint
        name: Next.js Linter
        entry: npm run lint
        language: system
        types_or: [javascript, jsx, ts, tsx]
        pass_filenames: false
